config/routes.rb
  post 'votes/vote/:resource_type/:resource_id(.:format)' => 'votes#vote', as: :vote
  delete 'votes/unvote/:resource_type/:resource_id(.:format)' => 'votes#unvote', as: :unvote
  get  'votes/for/:resource_type/:resource_id(.:format)' => 'votes#for', as: :votes_for
  get  'faves/:login(.:format)' => 'votes#by_login', as: :faves_by_login, constraints: { login: simplified_login_regex }

  resources :messages, :except => [:edit, :update] do
    collection do
      get :count
      get :new_messages
    end
    resources :flags
  end

  post '/oauth/assertion_token' => 'provider_oauth#assertion'
  get '/oauth/bounce' => 'provider_oauth#bounce', :as => "oauth_bounce"
  get '/oauth/bounce_back' => 'provider_oauth#bounce_back', :as => "oauth_bounce_back"
  use_doorkeeper do
    controllers applications: "oauth_applications",
                authorizations: "oauth_authorizations",
                authorized_applications: "oauth_authorized_applications",
                tokens: "oauth_tokens"
  end

  wiki_root '/pages'

  # Riparian routes
  resources :flow_tasks do
    member do
      get :run
    end
  end

  resources :observation_field_values, :only => [:create, :update, :destroy, :index]
  resources :observation_fields do
    member do
      get :merge
      put :merge, :to => 'observation_fields#merge_field'
    end
  end
  get '/' => 'welcome#index'
  get '/home' => 'users#dashboard', :as => :home
  get '/home.:format' => 'users#dashboard', :as => :formatted_home
  
  get '/users/edit' => 'users#edit', :as => "generic_edit_user"
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: "users/passwords"
  }
  devise_scope :user do
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post "session", :to => "users/sessions#create"
    get "signup", :to => "users/registrations#new"
    get "users/new", to: redirect( "signup" ), as: "new_user"
    # This *should* be a redirect, but that is messing with the way we're doing
    # get "/forgot_password", to: redirect( "/users/password/new" ), as: "forgot_password"
    get "/forgot_password", :to => "devise/passwords#new", :as => "forgot_password"
    put "users/update_session", :to => "users#update_session"
  end
  
  get '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  get '/help' => 'help#index', :as => :help
  get '/auth/failure' => 'provider_authorizations#failure', :as => :omniauth_failure
  post '/auth/:provider' => 'provider_authorizations#blank'
  get '/auth/:provider/callback' => 'provider_authorizations#create', :as => :omniauth_callback
  post '/auth/:provider/callback' => 'provider_authorizations#create', :as => :omniauth_callback_post
  delete '/auth/:provider/disconnect' => 'provider_authorizations#destroy', :as => :omniauth_disconnect
  delete "/provider_authorizations/:id" => 'provider_authorizations#destroy'
  get '/users/edit_after_auth' => 'users#edit_after_auth', :as => :edit_after_auth
  get '/facebook/photo_fields' => 'facebook#photo_fields'
  get "/eol/photo_fields" => "eol#photo_fields"
  get '/wikimedia_commons/photo_fields' => 'wikimedia_commons#photo_fields'
  post '/facebook' => 'facebook#index'
  
  resources :announcements do
    member do
      put :dismiss
    end
  end
  get '/users/dashboard' => 'users#dashboard', :as => :dashboard
  get '/users/curation' => 'users#curation', :as => :curate_users
  get '/users/updates_count' => 'users#updates_count', :as => :updates_count
  get '/users/new_updates' => 'users#new_updates', :as => :new_updates
  get '/users/api_token' => 'users#api_token', :as => :api_token
  get '/users/dashboard_updates' => 'users#dashboard_updates', :as => :dashboard_updates
  
  resources :users, :except => [:new, :create] do
    resources :flags
    collection do
      get :recent
      get :delete
      post :parental_consent
    end
    member do
      put :join_test
      put :leave_test
      put :merge
      put :trust
      put :untrust
    end
  end
  # resource :session
  # resources :passwords
  resources :people, :controller => :users, :except => [:create] do
    collection do
      get 'leaderboard(/:year(/:month))' => :leaderboard, :as => 'leaderboard_for'
    end
    member do
      get :moderation
    end
  end
  resources :relationships, controller: :relationships, only: [:index, :update, :destroy]
  get '/users/:id/suspend' => 'users#suspend', :as => :suspend_user, :constraints => { :id => /\d+/ }
  get '/users/:id/unsuspend' => 'users#unsuspend', :as => :unsuspend_user, :constraints => { :id => /\d+/ }
  post 'users/:id/add_role' => 'users#add_role', :as => :add_role, :constraints => { :id => /\d+/ }
  post 'users/set_spammer' => 'users#set_spammer'
  post 'users/:id/set_spammer' => 'users#set_spammer', :as => :set_spammer, :constraints => { :id => /\d+/ }
  delete 'users/:id/remove_role' => 'users#remove_role', :as => :remove_role, :constraints => { :id => /\d+/ }
  post "users/:id/mute" => "users#mute", as: :mute_user
  delete "users/:id/mute" => "users#unmute", as: :unmute_user
  post "users/:id/block" => "users#block", as: :block_user
  delete "users/:id/block" => "users#unblock", as: :unblock_user
  get 'photos/local_photo_fields' => 'photos#local_photo_fields', :as => :local_photo_fields
  put '/photos/:id/repair' => "photos#repair", :as => :photo_repair
  resources :photos, :only => [:show, :update, :destroy, :create] do
    resources :flags
    collection do
      get 'repair' => :fix
      post :repair_all
    end
    member do
      put :rotate
    end
  end
  delete 'google_photos/unlink' => 'picasa#unlink'
  
  post 'flickr/unlink_flickr_account' => 'flickr#unlink_flickr_account'
  get 'flickr/photos.:format' => 'flickr#photos'
  get "flickr/options" => "flickr#options", as: "flickr_options"

  resources :observation_photos, :only => [:show, :create, :update, :destroy]
  resources :observation_sounds, :only => [:show, :create, :update, :destroy]
  resources :soundcloud_sounds, :only => [:index]
  resources :sounds, only: [:show, :local_sound_fields, :create] do
    resources :flags
    collection do
      get :local_sound_fields
    end
  end
  resources :observations, :constraints => { :id => id_param_pattern } do
    resources :flags
    get 'fields', :as => 'extra_fields'
    get 'community_taxon_summary'
    collection do
      get :upload
      get :stats
      get :taxa
      get :taxon_stats
      get :user_stats
      get :accumulation
      get :phylogram
      get :export
      get :map
      get :identify
      get :moimport
      post :moimport
      get :torquemap
      get :compare
    end
    member do
      get :taxon_summary
      get :observation_links
      put :viewed_updates
      patch :update_fields
      post :review
      delete :review, as: "unreview"
    end
  end

  get 'observations/identotron' => 'observations#identotron', :as => :identotron
  post 'observations/update' => 'observations#update', :as => :update_observations
  get 'observations/new/batch_csv' => 'observations#new_batch_csv', :as => :new_observation_batch_csv
  match 'observations/new/batch' => 'observations#new_batch', :as => :new_observation_batch, :via => [:get, :post]
  post 'observations/new/bulk_csv' => 'observations#new_bulk_csv', :as => :new_observation_bulk_csv
  get 'observations/edit/batch' => 'observations#edit_batch', :as => :edit_observation_batch
  delete 'observations/delete_batch' => 'observations#delete_batch', :as => :delete_observation_batch
  get 'observations/import' => 'observations#import', :as => :import_observations
  match 'observations/import_photos' => 'observations#import_photos', :as => :import_photos, via: [:get, :post]
  post 'observations/import_sounds' => 'observations#import_sounds', :as => :import_sounds
  post 'observations/email_export/:id' => 'observations#email_export', :as => :email_export
  get 'observations/id_please' => 'observations#id_please', :as => :id_please
  get 'observations/selector' => 'observations#selector', :as => :observation_selector
  get '/observations/curation' => 'observations#curation', :as => :curate_observations
  get '/observations/widget' => 'observations#widget', :as => :observations_widget
  get 'observations/add_from_list' => 'observations#add_from_list', :as => :add_observations_from_list
  match 'observations/new_from_list' => 'observations#new_from_list', :as => :new_observations_from_list, via: [:get, :post]
  get 'observations/nearby' => 'observations#nearby', :as => :nearby_observations
  get 'observations/add_nearby' => 'observations#add_nearby', :as => :add_nearby_observations
  get 'observations/:id/edit_photos' => 'observations#edit_photos', :as => :edit_observation_photos
  post 'observations/:id/update_photos' => 'observations#update_photos', :as => :update_observation_photos
  get 'observations/:login' => 'observations#by_login', :as => :observations_by_login, :constraints => { :login => simplified_login_regex }
  get 'observations/:login.all' => 'observations#by_login_all', :as => :observations_by_login_all, :constraints => { :login => simplified_login_regex }
  get 'observations/:login.:format' => 'observations#by_login', :as => :observations_by_login_feed, :constraints => { :login => simplified_login_regex }
  get "observations/project/:id.:format" => "observations#project", as: :observations_for_project
  get 'observations/project/:id.all' => 'observations#project_all', :as => :all_project_observations
  match 'observations/:id/quality/:metric' => 'quality_metrics#vote', :as => :observation_quality, :via => [:post, :delete]

  match 'projects/:id/join' => 'projects#join', :as => :join_project, :via => [:get, :post]
  delete 'projects/:id/leave' => 'projects#leave', :as => :leave_project
  post 'projects/:id/add' => 'projects#add', :as => :add_project_observation

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  PLACEMENTS = %w(users/dashboard#sidebar users/dashboard welcome/index)
  has_and_belongs_to_many :sites
  validates_presence_of :placement, :start, :end, :body

  scope :in_locale, lambda {|locale|
    where("(? = ANY (locales)) OR locales IS NULL OR locales = '{}'", locale)
  }

  scope :in_specific_locale, lambda {|locale|
    where( "? = ANY (locales)", locale )
  }

  before_save :compact_locales

  def session_key
    "user-seen-ann-#{id}"
  end

  def compact_locales
    self.locales = ( locales || [] ).reject(&:blank?).compact
  end

  def dismissed_by?( user )
    return false unless dismissible?
    user_id = user.id if user.is_a?( User )
    user_id = user_id.to_i
    dismiss_user_ids.include?( user_id )
  end

  def self.active_in_placement( placement, site )
    scope = Announcement.
      joins( "LEFT OUTER JOIN announcements_sites ON announcements_sites.announcement_id = announcements.id").
      joins( "LEFT OUTER JOIN sites ON sites.id = announcements_sites.site_id" ).
      where( 'placement = ? AND ? BETWEEN "start" AND "end"', placement, Time.now.utc ).
      limit( 50 )
    base_scope = scope
    scope = scope.where( "sites.id = ?", site.id )
    @announcements = scope.in_specific_locale( I18n.locale )
    @announcements = scope.in_specific_locale( I18n.locale.to_s.split('-').first ) if @announcements.blank?
    @announcements = scope.in_locale( I18n.locale ) if @announcements.blank?
    @announcements = scope.in_locale( I18n.locale.to_s.split('-').first ) if @announcements.blank?
    if @announcements.blank?
      @announcements = base_scope.in_specific_locale( I18n.locale ).where( "sites.id IS NULL" )
      @announcements = base_scope.where( "sites.id IS NULL AND locales IS NULL" ) if @announcements.blank?
      @announcements = @announcements.flatten
    end
    @announcements = base_scope.where( "(locales IS NULL OR locales = '{}') AND sites.id IS NULL" ) if @announcements.blank?
    @announcements = @announcements.sort_by {|a| [
      a.site_ids.include?( @site.try(:id) ) ? 0 : 1,
      a.locales.include?( I18n.locale ) ? 0 : 1,
      a.id * -1
    ] }
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :site_admin_required, except: [:dismiss]
  before_filter :load_announcement, :only => [:show, :edit, :update, :destroy, :dismiss]
  before_filter :load_sites, only: [:new, :edit, :create]

  layout "bootstrap"
  
  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.order( "id desc" ).page( params[:page] )
    current_user_site_ids = current_user.site_admins.pluck(:site_id)
    unless current_user_site_ids.blank?
      @announcements = @announcements.joins(:sites).where( "sites.id": current_user_site_ids )
    end
    unless params[:q].blank?
      @announcements = @announcements.where( "body ilike ?", "%#{params[:q]}%" )
    end
  end
  
  def show
  end
  
  def new
    @announcement = Announcement.new
    if @site && !current_user.is_admin? && @site_admin = @site.site_admins.detect{|sa| sa.user_id == current_user.id }
      @announcement.sites = [@site]
    end
    respond_to do |format|
      format.html
    end
  end
  
  def edit
  end
  
  def create
    @announcement = Announcement.new(params[:announcement])
    if @site && !current_user.is_admin? && @site_admin = @site.site_admins.detect{|sa| sa.user_id == current_user.id }
      @announcement.sites = [@site]
    end
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement, :notice => t(:announcement_was_successfully_created)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => t(:announcement_was_successfully_updated)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end

  def dismiss
    unless @announcement.dismiss_user_ids.include?( current_user.id )
      @announcement.dismiss_user_ids << current_user.id
    end
    @announcement.save!
    respond_to do |format|
      format.any { head :ok }
      format.html { redirect_back_or_default( dashboard_path ) }
    end
  end
  
  private
  def load_announcement
    render_404 unless @announcement = Announcement.find_by_id(params[:id])
  end

  def load_sites
    @sites = Site.limit(100)
  end
  
end

app/views/announcements/_announcement.html.haml
- unless announcement.dismissed_by?( current_user )
  .announcement
    = announcement.body.html_safe
    - if announcement.dismissible? && current_user
      = button_to dismiss_announcement_path( announcement ), method: :put, remote: true, form_class: "dismiss-announcement", class: "dismiss-announcement-link", title: t(:dismiss) do
        %i.fa.fa-close

app/views/announcements/_form.html.haml
- content_for :extracss do
  :css
    #new_announcement textarea,
    .edit_announcement textarea {
      width: 100%;
      min-height: 300px;
    }
= form_for @announcement, :builder => DefaultFormBuilder do |f|
  = f.error_messages
  = f.select :placement, Announcement::PLACEMENTS
  :ruby
    month_names = I18n.t( "date.month_names" )
    if month_names.is_a?( Hash )
      month_names = [nil, I18n.t( "date.month_names" ).values].flatten
    end
  = f.datetime_select :start, use_month_names: month_names, order: [:year, :month, :day]
  = f.datetime_select :end, use_month_names: month_names, order: [:year, :month, :day]
  - if current_user.is_admin?
    = f.select :site_ids, @sites.map{ |s| [s.name, s.id] }, { include_blank: t(:all) }, multiple: true
  - else
    = f.hidden_field :site_ids
  = f.check_box :dismissible, label_after: true
  = f.select :locales, I18N_SUPPORTED_LOCALES, {}, { multiple: true, label: I18n.t( "locales_" ), description: t( "views.announcements.locales_desc" ) }
  = f.text_area :body
  .actions.buttons
    = f.submit f.object.new_record? ? t(:create) : t(:update), :class => "default button"
    = link_to t(:cancel), announcements_path, :class => "button"

app/views/announcements/edit.html.haml
.container
  .row
    .col-xs-12
      %h1= t :editing_announcement
      = render :partial => 'form'

app/views/announcements/index.html.haml
= content_for(:extracss) do
  :css
    #controls { display: flex; justify-content: space-between; }
    #controls .btn-primary { margin-right: 20px; }
    #controls form { max-width: 50%; }
    .sidebar-body { max-width: 360px; }
    .sidebar-body img, .general-body img { max-width: 100%; }
.container
  .row
    .col-xs-12
      %h1= t :announcements
      #controls.stacked
        = link_to t(:new_announcement), new_announcement_path, class: "btn btn-primary"
        = form_tag url_for, method: :get, class: "pull-right" do
          = hidden_fields_for_params
          .input-group
            = text_field_tag :q, params[:q], class: "form-control"
            .input-group-btn
              %button.btn.btn-default=t :search
      %table.table
        %thead
          %tr
            %th= t :placement
            %th= t :start
            %th= t :end
            %th= t :body
        %tbody
          - @announcements.each do |announcement|
            %tr
              %td= h announcement.placement
              %td=l announcement.start
              %td=l announcement.end
              %td
                - if announcement.placement === "users/dashboard#sidebar"
                  %div.sidebar-body=raw announcement.body
                - else
                  %div.general-body=raw announcement.body
              %td= link_to t(:show), announcement
              %td= link_to t(:edit), edit_announcement_path(announcement)
              %td= link_to t(:destroy), announcement, :data => {:confirm => t(:are_you_sure?)}, :method => :delete
      = will_paginate @announcements
      = link_to t(:new_announcement), new_announcement_path, class: "btn btn-primary"

app/views/announcements/new.html.haml
.container
  .row
    .col-xs-12
      %h2= t :new_announcement
      = render :partial => 'form'

app/views/announcements/show.html.haml
.container
  .row
    .col-xs-12
      %h2
        Announcement
        = @announcement.id
      %table.table.table-bordered
        - %w(created_at updated_at placement start end site_ids locales).each do |a|
          %tr
            %th=t "#{a}_", default: t( a )
            %td= @announcement.send( a )
        %tr
          %th=t :body
          - width = @announcement.placement === "users/dashboard#sidebar" ? "360px" : "100%"
          %td
            %div{style: "width: #{width};"}= raw @announcement.body
        - if @announcement.dismissible?
          %tr
            %th=t :dismissed_by
            %td
              = @announcement.dismiss_user_ids.size
              users
              - if @announcement.dismiss_user_ids.include?( current_user.id )
                including you
              = link_to_toggle_box "show user IDs" do
                = @announcement.dismiss_user_ids
      = link_to t(:edit), edit_announcement_path(@announcement)
      |
      = link_to t(:back), announcements_path