config/routes.rb
  get 'taxa/:id/children' => 'taxa#children', :as => :taxon_children
  get 'taxa/:id/children.:format' => 'taxa#children', :as => :formatted_taxon_children
  get 'taxa/:id/photos' => 'taxa#photos', as: :photos_of_taxon
  put 'taxa/:id/update_colors' => 'taxa#update_colors', :as => :update_taxon_colors
  match 'taxa/:id/add_places' => 'taxa#add_places', :as => :add_taxon_places, :via => [:get, :post]
  get 'taxa/flickr_tagger' => 'taxa#flickr_tagger', :as => :flickr_tagger
  get 'taxa/flickr_tagger.:format' => 'taxa#flickr_tagger', :as => :formatted_flickr_tagger
  post 'taxa/tag_flickr_photos'
  get 'taxa/flickr_photos_tagged'
  post 'taxa/tag_flickr_photos_from_observations'
  get 'taxa/search' => 'taxa#search', :as => :search_taxa
  get 'taxa/search.:format' => 'taxa#search', :as => :formatted_search_taxa
  get 'taxa/:action.:format' => 'taxa#index', :as => :formatted_taxa_action
  match 'taxa/:id/merge' => 'taxa#merge', :as => :merge_taxon, :via => [:get, :post]
  get 'taxa/:id/merge.:format' => 'taxa#merge', :as => :formatted_merge_taxon
  get 'taxa/:id/observation_photos' => 'taxa#observation_photos', :as => :taxon_observation_photos
  get 'taxa/observation_photos' => 'taxa#observation_photos'
  get 'taxa/:id/map' => 'taxa#map', :as => :taxon_map
  get 'taxa/map' => 'taxa#map', :as => :taxa_map
  get 'taxa/:id/range.:format' => 'taxa#range', :as => :taxon_range_geom
  get 'taxa/auto_complete_name' => 'taxa#auto_complete_name'
  get 'taxa/occur_in' => 'taxa#occur_in'
  get '/taxa/curation' => 'taxa#curation', :as => :curate_taxa
  get "taxa/*q" => 'taxa#try_show'
  
  resources :sources
  get 'journal' => 'posts#browse', :as => :journals
  get 'journal/:login' => 'posts#index', :as => :journal_by_login, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/' => 'posts#archives', :as => :journal_archives, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/:year/:month' => 'posts#archives', :as => :journal_archives_by_month, :constraints => { :month => /\d{1,2}/, :year => /\d{1,4}/, :login => simplified_login_regex }
  get 'journal/:login/:id/edit' => 'posts#edit', :as => :edit_journal_post
  resources :posts, :except => [:index], :constraints => { :id => id_param_pattern } do
    resources :flags
    collection do
      get :for_project_user
      get :for_user
    end
  end
  resources :posts,
    :as => 'journal_posts',
    :path => "/journal/:login",
    :constraints => { :login => simplified_login_regex } do
    resources :flags
  end
  resources :posts, as: "site_posts", path: "/blog" do
    resources :flags
    collection do
      get "archives/:year/:month" => "posts#archives", as: :archives_by_month, constraints: {
        month: /\d{1,2}/, 
        year: /\d{1,4}/
      }
      get :archives
    end
  end
  resources :trips, :constraints => { :id => id_param_pattern } do
    member do
      post :add_taxa_from_observations
      delete :remove_taxa
    end
    collection do
      get :tabulate
    end
  end
  get 'trips/:login' => 'trips#by_login', :as => :trips_by_login, :constraints => { :login => simplified_login_regex }
  
  resources :identifications, :constraints => { :id => id_param_pattern } do
    resources :flags
  end
  get 'identifications/bold' => 'identifications#bold'
  post 'identifications/agree' => 'identifications#agree'
  get 'identifications/:login' => 'identifications#by_login', :as => :identifications_by_login, :constraints => { :login => simplified_login_regex }
  resources :taxon_links
  
  get 'places/:id/widget' => 'places#widget', :as => :place_widget
  get 'places/guide_widget/:id' => 'places#guide_widget', :as => :place_guide_widget
  post '/places/find_external' => 'places#find_external', :as => :find_external
  get '/places/search' => 'places#search', :as => :place_search
  get '/places/:id/children' => 'places#children', :as => :place_children
  get 'places/:id/taxa.:format' => 'places#taxa', :as => :place_taxa
  get 'places/geometry/:id.:format' => 'places#geometry', :as => :place_geometry
  get 'places/guide/:id' => 'places#guide', :as => :place_guide
  get 'places/guide' => 'places#guide', :as => :idendotron_guide
  get 'places/cached_guide/:id' => 'places#cached_guide', :as => :cached_place_guide
  get 'places/autocomplete' => 'places#autocomplete', :as => :places_autocomplete
  resources :places do
    collection do
      get :planner
    end
    member do
      get :merge
      post :merge
    end
  end

  resources :flags
  resource :admin, only: :index, controller: :admin do
    collection do
      get :index
      get :queries
      get :stop_query
      get :users
      get "users/:id" => "admin#user_detail", as: :user_detail
      get :deleted_users
      put :grant_user_privilege
      put :revoke_user_privilege
      put :restore_user_privilege
      put :reset_user_privilege
    end
    resources :delayed_jobs, only: :index, controller: "admin/delayed_jobs" do
      member do
        get :unlock
      end
      collection do
        get :index
        get :active
        get :failed
        get :pending
      end
    end
  end
  get 'admin/user_content/:id/(:type)', :to => 'admin#user_content', :as => "admin_user_content"
  delete 'admin/destroy_user_content/:id/:type', :to => 'admin#destroy_user_content', :as => "destroy_user_content"
  put 'admin/update_user/:id', :to => 'admin#update_user', :as => "admin_update_user"

  resources :site_admins, only: [:create, :destroy] do
    collection do
      delete :destroy
    end
  end

  resource :stats do
    collection do
      get :index
      get :summary
      get :observation_weeks
      get :nps_bioblitz
      get :cnc2016
      get :cnc2017
      get :cnc2017_taxa
      get :cnc2017_stats
      get :canada_150
      get :parks_canada_2017
      get ":year", as: "year", to: "stats#year", constraints: { year: /\d+/ }
      get ":year/you", as: "your_year", to: "stats#your_year", constraints: { year: /\d+/ }
      get ":year/:login", as: "user_year", to: "stats#year", constraints: { year: /\d+/ }
      post :generate_year
    end
  end

  resources :taxon_ranges, :except => [:show]
  
  resources :atlases do
    member do
      post :alter_atlas_presence
      post :destroy_all_alterations
      post :remove_atlas_alteration
      post :remove_listed_taxon_alteration
      post :refresh_atlas
      get :get_defaults_for_taxon_place
    end
  end
  resources :exploded_atlas_places
  
  resources :complete_sets do
    member do
      post :destroy_relevant_listings
      post :remove_listed_taxon_alteration
      get :get_relevant_listings
    end
  end
  
  get '/calendar/:login' => 'calendars#index', :as => :calendar
  get '/calendar/:login/compare' => 'calendars#compare', :as => :calendar_compare
  get '/calendar/:login/:year/:month/:day' => 'calendars#show', :as => :calendar_date, :constraints => {
    :year => /\d+/,
    :month => /\d+/,
    :day => /\d+/
  }
  
  resources :subscriptions, :only => [:index, :new, :edit, :create, :update, :destroy]
  delete 'subscriptions/:resource_type/:resource_id' => "subscriptions#destroy", :as => :delete_subscription
  get 'subscriptions/:resource_type/:resource_id/edit' => "subscriptions#edit", :as => :edit_subscription_by_resource
  post 'subscriptions/:resource_type/:resource_id/subscribe' => 'subscriptions#subscribe', as: :subscribe

  resources :taxon_changes, constraints: { id: id_param_pattern } do
    resources :taxon_change_taxa, controller: :taxon_change_taxa, shallow: true
    collection do
      get "group/:group" => "taxon_changes#group", as: :group
    end
    put :commit
    get :commit_for_user
    put "commit_record/:type/:record_id/to/:taxon_id" => "taxon_changes#commit_records", as: :commit_record
    put "commit_records/:type/(to/:taxon_id)" => "taxon_changes#commit_records", as: :commit_records
  end
  resources :taxon_schemes, :only => [:index, :show], :constraints => {:format => [:html]}
  get 'taxon_schemes/:id/mapped_inactive_taxa' => 'taxon_schemes#mapped_inactive_taxa', :as => :mapped_inactive_taxa
  get 'taxon_schemes/:id/orphaned_inactive_taxa' => 'taxon_schemes#orphaned_inactive_taxa', :as => :orphaned_inactive_taxa
  
  resources :taxon_framework_relationships
  get 'taxon_frameworks/:id/relationship_unknown' => 'taxon_frameworks#relationship_unknown', :as => :relationship_unknown
  
  resources :taxon_frameworks, except: [:show, :index]
  
  resources :taxon_splits, :controller => :taxon_changes
  resources :taxon_merges, :controller => :taxon_changes
  resources :taxon_swaps, :controller => :taxon_changes
  resources :taxon_drops, :controller => :taxon_changes
  resources :taxon_stages, :controller => :taxon_changes
  resources :conservation_statuses, :only => [:autocomplete]

  resource :computer_vision_demo, only: :index, controller: :computer_vision_demo do
  end
  resources :computer_vision_demo_uploads do
    member do
      post :score
    end
  end
  resources :user_parents, only: [:index, :new, :create, :destroy] do
    member do
      get :confirm
    end
  end
  resources :moderator_actions, only: [:create]

  resource :lifelists, only: [] do
    collection do
      get ":login", to: "lifelists#by_login", as: "by_login"
    end
  end

  get "/google_photos(/:action(/:id))", controller: :picasa

  get 'translate' => 'translations#index', :as => :translate_list
  post 'translate/translate' => 'translations#translate', :as => :translate
  get 'translate/reload' => 'translations#reload', :as => :translate_reload

  # Hack to enable mail previews. You could also remove get
  # '/:controller(/:action(/:id))' but that breaks a bunch of other stuff. You
  # could also fix that other stuff, if you're weren't a horrible person, but
  # you are.
  unless Rails.env.production?
    get '/rails/mailers/*path' => 'rails/mailers#preview'
  end
  get '/:controller(/:action(/:id))'

  match '/404', to: 'errors#error_404', via: :all

app/controllers/atlases_controller.rb
class AtlasesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :curator_required, :only => [:new, :create, :edit, :update,
    :destroy, :alter_atlas_presence, :destroy_all_alterations, :remove_atlas_alteration,
    :remove_listed_taxon_alteration, :refresh_atlas]
  before_filter :find_atlas, except: [ :new, :create, :index ]
  layout "bootstrap"

  def new
    @atlas = Atlas.new( taxon_id: params[:taxon_id].to_i )
  end

  def edit
    load_for_edit
  end

  def show
    @atlas_places = @atlas.places
    @atlas_presence_places_with_establishment_means = @atlas.presence_places_with_establishment_means
    @atlas_presence_places_with_establishment_means_hash = Hash[@atlas_presence_places_with_establishment_means.map{ |e| [ e[:id], e[:establishment_means] ] }]
    @exploded_places = Hash[@atlas.exploded_atlas_places.map{ |e| [ e.place_id, e.id ] }]
    @atlas_presence_places_with_establishment_means_hash_json = @atlas_presence_places_with_establishment_means_hash.to_json
    @exploded_places_json = @exploded_places.to_json
    
    #any obs outside of the atlas
    @observations_not_in_atlas_places_params = { 
      taxon_id: @atlas.taxon_id, 
      quality_grade: ["research","needs_id"].join( "," ),
      geoprivacy: ["open,obscured"].join( "," ),
      not_in_place: @atlas_presence_places_with_establishment_means.map{|p| p[:id] }.join( "," )
    }
    @num_obs_not_in_atlas_places = INatAPIService.observations( @observations_not_in_atlas_places_params.merge( per_page: 0 ) ).total_results
    respond_to do |format|
      format.html do
        @is_curator = "#{current_user.is_curator?}"
        @atlas_alterations = @atlas.atlas_alterations.includes( :place, :user ).order( "created_at DESC" ).
          limit( 30 ).reverse
        @listed_taxon_alterations = @atlas.relevant_listed_taxon_alterations.includes( :place, :user ).
          order( "listed_taxon_alterations.created_at DESC" ).limit( 30 ).reverse
      end
      format.json { render json: {
          presence_places: @atlas_presence_places_with_establishment_means_hash,
          exploded_places: @exploded_places
        }
      }
    end
  end
  
  def index
    filter_params = params[:filters] || params
    @taxon = Taxon.find_by_id( filter_params[:taxon_id].to_i ) unless filter_params[:taxon_id].blank?
    @is_active = filter_params[:is_active]
    @is_marked = filter_params[:is_marked]
    
    scope = Atlas.all
    scope = scope.taxon(@taxon) if @taxon
    if @is_active.yesish?
      scope = scope.active
    elsif @is_active.noish?
      scope = scope.inactive
    end
    if @is_marked.yesish?
      scope = scope.marked
    elsif @is_marked.noish?
      scope = scope.unmarked
    end
    
    @atlases = scope.page(params[:page]).per_page(10)
  end

  def create
    @atlas = Atlas.new( params[:atlas].merge(:user_id => current_user.id) )
    respond_to do |format|
      if @atlas.save
        format.html { redirect_to( @atlas, notice: "Atlas was successfully created." ) }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @atlas.update_attributes( params[:atlas] )
        @atlas.taxon
        format.html { redirect_to( @atlas, notice: "Atlas was successfully updated." ) }
      else
        load_for_edit
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @atlas.destroy
    respond_to do |format|
      format.html { redirect_to( @atlas.taxon ) }
    end
  end

  ## Custom actions ############################################################

  def alter_atlas_presence
    taxon_id = params[:taxon_id]
    place_id = params[:place_id]
    place = Place.find( place_id )
    taxon = Taxon.find( taxon_id )
    lts = taxon.atlas.get_atlas_presence_place_listed_taxa( place_id )
    error = nil
    if lts.count > 0
      lts.each do |lt|
        lt.updater = current_user
        lt.destroy
      end
      presence = false
    else
      list = place.check_list

      # If there are other potentially relevant comprehensive lists, those
      # need to be added to as well otherwise the validation for our new
      # listed taxon will fail
      comprehensive_ancestor_check_lists = CheckList.where(
        "comprehensive AND lists.taxon_id IN (?) AND lists.place_id IN (?)",
        taxon.ancestor_ids, place.self_and_ancestor_ids
      )
      if comprehensive_ancestor_check_lists.exists?
        ancestor_place_ids = place.ancestor_ids
        # Order these by higher ranked taxa and higher ranked places
        comprehensive_ancestor_check_lists = comprehensive_ancestor_check_lists.
          includes(:taxon).
          limit( 500 ).
          sort_by{ |cl| [cl.taxon.rank_level.to_i * -1, ancestor_place_ids.index(cl.place_id).to_i ]}
        comprehensive_ancestor_check_lists.each do |check_list|
          check_list.add_taxon( taxon, user: current_user )
        end
      end

      lt = list.listed_taxa.find_by_taxon_id( taxon_id )
      lt ||= ListedTaxon.create( taxon_id: taxon_id, place_id: place_id, list_id: list.id, user_id: current_user.id )

      if lt.errors.any?
        presence = "not allowed"
        error = lt.errors.full_messages.to_sentence
      else
        presence = true
      end
    end


    unless presence
      comprehensive_list = place.check_lists.where( "comprehensive AND lists.taxon_id IN (?)", taxon.self_and_ancestor_ids ).first
      if comprehensive_list && comprehensive_lt = comprehensive_list.listed_taxa.where( taxon: taxon ).first
        comprehensive_lt.updater = current_user
        comprehensive_lt.destroy
      end
    end

    respond_to do |format|
      format.json do
        if error
          render json: { place_name: place.try_methods( :display_name, :name ), place_id: place_id, presence: presence, error: error }, status: :unprocessable_entity
        else
          render json: { place_name: place.try_methods( :display_name, :name ), place_id: place_id, presence: presence }, status: :ok
        end
      end
    end
  end

  def destroy_all_alterations
    atlas_id = @atlas.id
    AtlasAlteration.where( atlas_id: atlas_id ).destroy_all
    respond_to do |format|
      format.json { render json: {}, status: :ok }
    end
  end

  def remove_atlas_alteration
    aa_id = params[:aa_id]
    aa = AtlasAlteration.find( aa_id )
    aa.destroy
    respond_to do |format|
      format.json { render json: {}, status: :ok}
    end
  end

  def remove_listed_taxon_alteration
    lta_id = params[:lta_id]
    lta = ListedTaxonAlteration.find( lta_id )
    lta.destroy
    respond_to do |format|
      format.json { render json: {}, status: :ok }
    end
  end

  def get_defaults_for_taxon_place
    taxon_id = params[:taxon_id]
    place_id = params[:place_id]
    lt = ListedTaxon.get_defaults_for_taxon_place( place_id, taxon_id, { limit: 10 } )
    render json: lt, include: { taxon: { only: :name }, place: { only: [:name, :display_name] } }, only: :id
  end
  
  def refresh_atlas
    is_marked = Atlas.still_is_marked(@atlas)
    respond_to do |format|
      format.json { render json: is_marked, status: :ok }
    end
  end

  private

  def find_atlas
    begin
      @atlas = Atlas.find( params[:id] )
    rescue
      render_404
    end
  end

  def load_for_edit
    @exploded_atlas_places = @atlas.exploded_atlas_places.includes( :place )
    @atlas_places = @atlas.places
  end

end

app/views/atlases/_form_fields.html.haml
- content_for :extrajs do
  :javascript
    var taxon = #{ @atlas.taxon ? @atlas.taxon.as_indexed_json.to_json.html_safe : "null" };
    $( ".taxonchooser" ).taxonAutocomplete( {
      idEl: $( "#atlas_taxon_id" ),
      initialSelection: taxon ? new iNatModels.Taxon( taxon ) : null
    } );
.row.stacked
  .col-xs-12
    - if @atlas.new_record?
      = text_field_tag :taxon_name, @atlas.taxon.try( :name ), class: "taxonchooser form-control"
      = f.hidden_field :taxon_id
.row
  .col-xs-12
    = f.radio_button :is_active, true, label_after: true, label: t( :active ).titleize
    = f.radio_button :is_active, false, label_after: true, label: t( :inactive ).titleize

app/views/atlases/edit.html.haml
- content_for :extrahead do
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"
  = javascript_include_tag "atlases/edit"

.container
  .row
    .col-xs-12
      %h2.pull-left
        =t :edit_atlas_for_taxon_html, taxon: link_to( @atlas.taxon.name, @atlas.taxon )
  = form_for( @atlas, :builder => DefaultFormBuilder, html: { multipart: true } ) do |f|
    = f.error_messages
    = render :partial => "form_fields", locals: { f: f }
    = f.submit t( :update ), class: "btn btn-primary"
  .row
    .col-xs-12
      %h3
        = "Exploded Atlas Places"
      %table.table.table-striped
        %thead
          %tr
            %th="Place"
            %th="Action"
        %tbody.exploded
          - @exploded_atlas_places.each do |exploded_atlas_place|
            %tr
              %td= link_to exploded_atlas_place.place.try_methods( :display_name, :name ), exploded_atlas_place.place
              %td= link_to "collapse", exploded_atlas_place_path(exploded_atlas_place), id: exploded_atlas_place.id, class: "collapse_button"
      - if @exploded_atlas_places.count == 0
        .no_exploded="No atlas places have been exploded"
      %h3
        = "Atlas Places"
      %table.table.table-striped
        %thead
          %tr
            %th="Place"
            %th="Action"
        %tbody.places
          - @atlas_places.each do |atlas_place|
            %tr
              %td= link_to atlas_place.display_name, atlas_place
              %td= link_to "explode", exploded_atlas_places_path, :id => "#{atlas_place.id}_#{@atlas.id}", :class => "explode_button"
      
      = link_to t(:back), @atlas, class: "btn btn-default"
      = link_to t(:delete), @atlas, method: :delete, data: { confirm: "are you sure?" }, class: "btn btn-danger pull-right"

app/views/atlases/index.html.haml
:ruby
  if @taxon
    @taxon.html = render( partial: "taxa/chooser.html.erb", object: @taxon )
  end
  @default_taxa = Taxon::ICONIC_TAXA.map do |taxon|
    taxon.html = render( partial: "taxa/chooser.html.erb", object: taxon )
    taxon
  end
- content_for :extrahead do
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"
  = javascript_include_tag "atlases/index"
- content_for( :extracss ) do
  = stylesheet_link_tag "autocomplete"
- content_for( :extrajs ) do
  :javascript
    window.taxon = #{ json_escape @taxon.to_json( methods: [:html] ).html_safe }
    window.defaultTaxa = #{ json_escape @default_taxa.to_json( methods: [:html] ).html_safe }
    $( document ).ready( function() {      
      $( "#filters_taxon_name" ).taxonAutocomplete( {
        idEl: $( "#filters_taxon_id" ),
        initialSelection: #{ raw @taxon.to_json },
        thumbnail: false,
        bootstrapClear: true
      } );
      
    } )
.container
  .row
    .col-xs-12
      %h2.pull-left
        = "Atlases"
      .pull-right= link_to "Create an atlas", new_atlas_path, class: "btn btn-default"
  .panel.panel-info
    .panel-heading
      %h3.panel-title
        = "About Atlases"
    .panel-body
      %p
        = "Atlases convey the global distribution of a taxon. Curators make atlases by defining the structure"
        = "of an atlas and curating the listed taxa that drive it."
        = link_to "Learn more", "/pages/atlases"
  = "All active atlases are checked daily and marked if relevant observatons fall out of range."
  = "Any marked atlases are listed below."
  = "Once you've resolved any issues, manually refresh the atlas to unmark it."
  .row
    .col-xs-3
      = form_for :filters, builder: DefaultFormBuilder, html: { method: :get } do |f|
        = f.text_field :taxon_name, placeholder: t(:type_taxon_name), label: t(:taxon_including_descendants)
        = f.hidden_field :taxon_id, value: @taxon ? @taxon.id : nil
        = f.select :is_active, [t( :true ), t( :false )], include_blank: t( :any_ ), selected: @is_active, label: t( :active )
        = f.select :is_marked, [t( :true ), t( :false )], include_blank: t( :any_ ), selected: @is_marked, label: t( :marked )
        = f.submit t( :filter ), class: "default button", "data-loading-click": t( :filtering )
        = link_to t( :clear_filters ), atlases_url, class: "minor button"
    .col-xs-9
      %table.table.table-striped
        %thead
          %tr
            %th="Atlas"
            %th="Active"
            %th="Marked"
            %th=""
          %tbody.exploded
            - @atlases.each do |atlas|
              %tr
                %td 
                  = "Atlas for"
                  = render partial: "shared/taxon", locals: { taxon: atlas.taxon, named_ancestor: true, link_url: atlas }
                  %td= atlas.is_active
                  %td= atlas.is_marked
                  %td= link_to "refresh atlas", "#", :class => "refresh_button", :data => { atlas_id: atlas.id }
      = will_paginate @atlases
      - if @atlases.empty?
        = "No atlases"

app/views/atlases/new.html.haml
.container
  .row
    .col-xs-12
      %h2= "New Atlas"
  = form_for(@atlas, :builder => DefaultFormBuilder, :html => {:multipart => true}) do |f|
    = f.error_messages
    = render :partial => 'form_fields', :locals => {:f => f}
    = f.submit t(:create), :class => "btn btn-primary"
    = link_to t(:back), @atlas.taxon || taxa_path, :class => "btn btn-default"

app/views/atlases/show.html.haml
- content_for :title do
  Atlas for
  = render "taxa/taxon.txt.erb", taxon: @atlas.taxon

- content_for :extrajs do
  = javascript_include_tag "atlases/show"

- content_for :extracss do
  = stylesheet_link_tag "atlases/show"

.container
  .row
    .col-xs-12
      - unless @atlas.is_active
        .alert.alert-info{ role: :alert }
          This atlas is currently not active
      - if @num_obs_not_in_atlas_places > 0
        .alert.alert-warning{ role: :alert }
          Warning: there are observations not represented by this atlas
          = link_to t( :view ), observations_path( @observations_not_in_atlas_places_params )
      %h2.pull-left
        =t :atlas_for_taxon_html, taxon: render( "shared/taxon", taxon: @atlas.taxon, named_ancestor: true, link_url: @atlas.taxon )
      - if current_user.is_curator?
        .pull-right= link_to t( :edit ), edit_atlas_path( @atlas )
  .row.cf#top
    .col-sm-3.col-xs-12.pull-right
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            = "About Atlases"
        .panel-body
          %p
            = "Atlases convey the global distribution of a taxon. Curators make atlases by defining the structure"
            = "of an atlas and curating the listed taxa that drive it."
            = link_to "Learn more", "/pages/atlases"
          %img.media-object{ src: "https://static.inaturalist.org/wiki_page_attachments/720-original.png", class: "img-responsive" }
      .content-entry#right
      .content-entry#bottomright
    .col-sm-9.col-xs-12.pull-left#left
      :ruby
        map_attributes = setup_map_tag_attrs(
          min_zoom: 1,
          show_all_layer: false,
          taxon_layers: [ {
            taxon: @atlas.taxon,
            places: false,
            ranges: true,
            observations: true,
            gbif: { disabled: true },
          } ]
        )
        atlas_data = {
          atlas_id: @atlas.id,
          taxon_id: @atlas.taxon_id,
          place_ids: @atlas_presence_places_with_establishment_means_hash_json,
          exploded_places: @exploded_places_json,
          is_curator: @is_curator
        }
        map_attributes["data"] = map_attributes["data"].merge( atlas_data )
      #map{ map_attributes }
  
  #bottom
    #comments
      = render partial: "comments/comments", object: @atlas
    
    %h3
      = "Recent Atlas Alterations"

    %table.table.table-striped
      %thead
        %tr
          %th= "Place"
          %th= "Action"
          %th= "Login"
          %th= "Date"
          %th= ""
      %tbody#alteration
        - @atlas_alterations.each do |atlas_alteration|
          %tr
            %th{:scope => "row" }= link_to atlas_alteration.place.try_methods( :display_name, :name ), atlas_alteration.place
            %td= atlas_alteration.action
            %td= atlas_alteration.user.nil? ? "" : ( link_to atlas_alteration.user.login, atlas_alteration.user )
            %td= atlas_alteration.created_at
            -if current_user.is_curator?
              %td= link_to "remove", "#", :class => "remove_atlas_alteration", :data => { atlas_alteration_id: atlas_alteration.id }

    - if @atlas_alterations.count == 0
      .no_alterations= "No alterations to this atlas yet"

    %h3
      = "Recent Listed Taxon Alterations"

    %table.table.table-striped
      %thead
        %tr
          %th= "Place"
          %th= "Taxon"
          %th= "Action"
          %th= "Login"
          %th= "Date"
          %th=""
      %tbody#listed_taxon_alteration
        - @listed_taxon_alterations.each do |listed_taxon_alteration|
          %tr
            %th{ :scope => "row" }= link_to listed_taxon_alteration.place.try_methods( :display_name, :name ), listed_taxon_alteration.place
            %td= link_to listed_taxon_alteration.taxon.name, listed_taxon_alteration.taxon
            %td= listed_taxon_alteration.action
            %td= listed_taxon_alteration.user.nil? ? "" : ( link_to listed_taxon_alteration.user.login, listed_taxon_alteration.user )
            %td= listed_taxon_alteration.created_at
            -if current_user.is_curator?
              %td= link_to "remove", "#", :class => "remove_listed_taxon_alteration", :data => { listed_taxon_alteration_id: listed_taxon_alteration.id }

    - if @listed_taxon_alterations.count == 0
      .no_listed_taxon_alterations= "No listed taxon alterations relevant to this atlas yet"
    - if @atlas.user
      .pull-right
        = link_to @atlas.user.login, @atlas.user
        = "created this atlas on #{l(@atlas.created_at.to_date, :format => :long)}"