config/routes.rb
  get 'taxa/:id/children' => 'taxa#children', :as => :taxon_children
  get 'taxa/:id/children.:format' => 'taxa#children', :as => :formatted_taxon_children
  get 'taxa/:id/photos' => 'taxa#photos', as: :photos_of_taxon
  put 'taxa/:id/update_colors' => 'taxa#update_colors', :as => :update_taxon_colors
  match 'taxa/:id/add_places' => 'taxa#add_places', :as => :add_taxon_places, :via => [:get, :post]
  get 'taxa/flickr_tagger' => 'taxa#flickr_tagger', :as => :flickr_tagger
  get 'taxa/flickr_tagger.:format' => 'taxa#flickr_tagger', :as => :formatted_flickr_tagger
  post 'taxa/tag_flickr_photos'
  get 'taxa/flickr_photos_tagged'
  post 'taxa/tag_flickr_photos_from_observations'
  get 'taxa/search' => 'taxa#search', :as => :search_taxa
  get 'taxa/search.:format' => 'taxa#search', :as => :formatted_search_taxa
  get 'taxa/:action.:format' => 'taxa#index', :as => :formatted_taxa_action
  match 'taxa/:id/merge' => 'taxa#merge', :as => :merge_taxon, :via => [:get, :post]
  get 'taxa/:id/merge.:format' => 'taxa#merge', :as => :formatted_merge_taxon
  get 'taxa/:id/observation_photos' => 'taxa#observation_photos', :as => :taxon_observation_photos
  get 'taxa/observation_photos' => 'taxa#observation_photos'
  get 'taxa/:id/map' => 'taxa#map', :as => :taxon_map
  get 'taxa/map' => 'taxa#map', :as => :taxa_map
  get 'taxa/:id/range.:format' => 'taxa#range', :as => :taxon_range_geom
  get 'taxa/auto_complete_name' => 'taxa#auto_complete_name'
  get 'taxa/occur_in' => 'taxa#occur_in'
  get '/taxa/curation' => 'taxa#curation', :as => :curate_taxa
  get "taxa/*q" => 'taxa#try_show'
  
  resources :sources
  get 'journal' => 'posts#browse', :as => :journals
  get 'journal/:login' => 'posts#index', :as => :journal_by_login, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/' => 'posts#archives', :as => :journal_archives, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/:year/:month' => 'posts#archives', :as => :journal_archives_by_month, :constraints => { :month => /\d{1,2}/, :year => /\d{1,4}/, :login => simplified_login_regex }
  get 'journal/:login/:id/edit' => 'posts#edit', :as => :edit_journal_post
  resources :posts, :except => [:index], :constraints => { :id => id_param_pattern } do
    resources :flags
    collection do
      get :for_project_user
      get :for_user
    end
  end
  resources :posts,
    :as => 'journal_posts',
    :path => "/journal/:login",
    :constraints => { :login => simplified_login_regex } do
    resources :flags
  end
  resources :posts, as: "site_posts", path: "/blog" do
    resources :flags
    collection do
      get "archives/:year/:month" => "posts#archives", as: :archives_by_month, constraints: {
        month: /\d{1,2}/, 
        year: /\d{1,4}/
      }
      get :archives
    end
  end
  resources :trips, :constraints => { :id => id_param_pattern } do
    member do
      post :add_taxa_from_observations
      delete :remove_taxa
    end
    collection do
      get :tabulate
    end
  end
  get 'trips/:login' => 'trips#by_login', :as => :trips_by_login, :constraints => { :login => simplified_login_regex }
  
  resources :identifications, :constraints => { :id => id_param_pattern } do
    resources :flags
  end
  get 'identifications/bold' => 'identifications#bold'
  post 'identifications/agree' => 'identifications#agree'
  get 'identifications/:login' => 'identifications#by_login', :as => :identifications_by_login, :constraints => { :login => simplified_login_regex }
  resources :taxon_links
  
  get 'places/:id/widget' => 'places#widget', :as => :place_widget
  get 'places/guide_widget/:id' => 'places#guide_widget', :as => :place_guide_widget
  post '/places/find_external' => 'places#find_external', :as => :find_external
  get '/places/search' => 'places#search', :as => :place_search
  get '/places/:id/children' => 'places#children', :as => :place_children
  get 'places/:id/taxa.:format' => 'places#taxa', :as => :place_taxa
  get 'places/geometry/:id.:format' => 'places#geometry', :as => :place_geometry
  get 'places/guide/:id' => 'places#guide', :as => :place_guide
  get 'places/guide' => 'places#guide', :as => :idendotron_guide
  get 'places/cached_guide/:id' => 'places#cached_guide', :as => :cached_place_guide
  get 'places/autocomplete' => 'places#autocomplete', :as => :places_autocomplete
  resources :places do
    collection do
      get :planner
    end
    member do
      get :merge
      post :merge
    end
  end

  resources :flags
  resource :admin, only: :index, controller: :admin do
    collection do
      get :index
      get :queries
      get :stop_query
      get :users
      get "users/:id" => "admin#user_detail", as: :user_detail
      get :deleted_users
      put :grant_user_privilege
      put :revoke_user_privilege
      put :restore_user_privilege
      put :reset_user_privilege
    end
    resources :delayed_jobs, only: :index, controller: "admin/delayed_jobs" do
      member do
        get :unlock
      end
      collection do
        get :index
        get :active
        get :failed
        get :pending
      end
    end
  end
  get 'admin/user_content/:id/(:type)', :to => 'admin#user_content', :as => "admin_user_content"
  delete 'admin/destroy_user_content/:id/:type', :to => 'admin#destroy_user_content', :as => "destroy_user_content"
  put 'admin/update_user/:id', :to => 'admin#update_user', :as => "admin_update_user"

  resources :site_admins, only: [:create, :destroy] do
    collection do
      delete :destroy
    end
  end

  resource :stats do
    collection do
      get :index
      get :summary
      get :observation_weeks
      get :nps_bioblitz
      get :cnc2016
      get :cnc2017
      get :cnc2017_taxa
      get :cnc2017_stats
      get :canada_150
      get :parks_canada_2017
      get ":year", as: "year", to: "stats#year", constraints: { year: /\d+/ }
      get ":year/you", as: "your_year", to: "stats#your_year", constraints: { year: /\d+/ }
      get ":year/:login", as: "user_year", to: "stats#year", constraints: { year: /\d+/ }
      post :generate_year
    end
  end

  resources :taxon_ranges, :except => [:show]
  
  resources :atlases do
    member do
      post :alter_atlas_presence
      post :destroy_all_alterations
      post :remove_atlas_alteration
      post :remove_listed_taxon_alteration
      post :refresh_atlas
      get :get_defaults_for_taxon_place
    end
  end
  resources :exploded_atlas_places
  
  resources :complete_sets do
    member do
      post :destroy_relevant_listings
      post :remove_listed_taxon_alteration
      get :get_relevant_listings
    end
  end
  
  get '/calendar/:login' => 'calendars#index', :as => :calendar
  get '/calendar/:login/compare' => 'calendars#compare', :as => :calendar_compare
  get '/calendar/:login/:year/:month/:day' => 'calendars#show', :as => :calendar_date, :constraints => {
    :year => /\d+/,
    :month => /\d+/,
    :day => /\d+/
  }
  
  resources :subscriptions, :only => [:index, :new, :edit, :create, :update, :destroy]
  delete 'subscriptions/:resource_type/:resource_id' => "subscriptions#destroy", :as => :delete_subscription
  get 'subscriptions/:resource_type/:resource_id/edit' => "subscriptions#edit", :as => :edit_subscription_by_resource
  post 'subscriptions/:resource_type/:resource_id/subscribe' => 'subscriptions#subscribe', as: :subscribe

  resources :taxon_changes, constraints: { id: id_param_pattern } do
    resources :taxon_change_taxa, controller: :taxon_change_taxa, shallow: true
    collection do
      get "group/:group" => "taxon_changes#group", as: :group
    end
    put :commit
    get :commit_for_user
    put "commit_record/:type/:record_id/to/:taxon_id" => "taxon_changes#commit_records", as: :commit_record
    put "commit_records/:type/(to/:taxon_id)" => "taxon_changes#commit_records", as: :commit_records
  end
  resources :taxon_schemes, :only => [:index, :show], :constraints => {:format => [:html]}
  get 'taxon_schemes/:id/mapped_inactive_taxa' => 'taxon_schemes#mapped_inactive_taxa', :as => :mapped_inactive_taxa
  get 'taxon_schemes/:id/orphaned_inactive_taxa' => 'taxon_schemes#orphaned_inactive_taxa', :as => :orphaned_inactive_taxa
  
  resources :taxon_framework_relationships
  get 'taxon_frameworks/:id/relationship_unknown' => 'taxon_frameworks#relationship_unknown', :as => :relationship_unknown
  
  resources :taxon_frameworks, except: [:show, :index]
  
  resources :taxon_splits, :controller => :taxon_changes
  resources :taxon_merges, :controller => :taxon_changes
  resources :taxon_swaps, :controller => :taxon_changes
  resources :taxon_drops, :controller => :taxon_changes
  resources :taxon_stages, :controller => :taxon_changes
  resources :conservation_statuses, :only => [:autocomplete]

  resource :computer_vision_demo, only: :index, controller: :computer_vision_demo do
  end
  resources :computer_vision_demo_uploads do
    member do
      post :score
    end
  end
  resources :user_parents, only: [:index, :new, :create, :destroy] do
    member do
      get :confirm
    end
  end
  resources :moderator_actions, only: [:create]

  resource :lifelists, only: [] do
    collection do
      get ":login", to: "lifelists#by_login", as: "by_login"
    end
  end

  get "/google_photos(/:action(/:id))", controller: :picasa

  get 'translate' => 'translations#index', :as => :translate_list
  post 'translate/translate' => 'translations#translate', :as => :translate
  get 'translate/reload' => 'translations#reload', :as => :translate_reload

  # Hack to enable mail previews. You could also remove get
  # '/:controller(/:action(/:id))' but that breaks a bunch of other stuff. You
  # could also fix that other stuff, if you're weren't a horrible person, but
  # you are.
  unless Rails.env.production?
    get '/rails/mailers/*path' => 'rails/mailers#preview'
  end
  get '/:controller(/:action(/:id))'

  match '/404', to: 'errors#error_404', via: :all

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :resource, :polymorphic => true, :inverse_of => :update_subscriptions
  belongs_to :user
  belongs_to :taxon # in case this subscription has taxonomic specifity

  blockable_by lambda {|subscription| subscription.resource.try(:user_id) }

  after_save :clear_caches
  after_destroy :clear_caches
  
  validates_presence_of :resource, :user
  validates_uniqueness_of :user_id, :scope => [:resource_type, :resource_id, :taxon_id], 
    :message => "has already subscribed to this resource"
  validate :cannot_subscribe_to_north_america

  cattr_accessor :subscribable_classes
  @@subscribable_classes ||= []

  scope :with_unsuspended_users, -> {
    joins(:user).where(users: { subscriptions_suspended_at: nil }) }

  def to_s
    "<Subscription #{id} user: #{user_id} resource: #{resource_type} #{resource_id}>"
  end

  def self.users_with_unviewed_updates_from(notifier)
    es_response = UpdateAction.elastic_search(
      filters: [
        { term: { notifier_type: notifier.class.to_s } },
        { term: { notifier_id: notifier.id } }
      ],
      sort: { id: :desc }
    ).per_page(100).page(1)
    if es_response && es_response.results
      subscriber_ids = []
      viewed_subscriber_ids = []
      es_response.results.each do |result|
        subscriber_ids += result.subscriber_ids
        viewed_subscriber_ids += result.viewed_subscriber_ids
      end
      return subscriber_ids.uniq - viewed_subscriber_ids.uniq
    end
    []
  end

  def cannot_subscribe_to_north_america
    return unless resource_type == "Place"
    return unless taxon_id.blank?
    if Place.north_america && resource_id == Place.north_america.id
      errors.add(:resource_id, "cannot subscribe to North America without conditions")
    end
  end

  def clear_caches
    ctrl = ActionController::Base.new
    ctrl.send :expire_action, FakeView.home_url( user_id: user_id, ssl: true )
    ctrl.send :expire_action, FakeView.home_url( user_id: user_id, ssl: false )
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_subscription, :except => [:new, :create, :index, :edit, :subscribe]
  before_filter :load_resource, only: [:subscribe]
  before_filter :require_owner, :except => [:new, :create, :index, :edit, :subscribe]
  before_filter :return_here, :only => [:index]
  
  def index
    @type = params[:type]
    @type = "place" unless Subscription.subscribable_classes.map(&:underscore).include?(@type)
    resource_type = @type.camelcase
    @subscriptions = current_user.subscriptions.includes(:resource).
      where("resource_type = ?", resource_type).
      order("subscriptions.id desc").
      page(params[:page])
  end

  def new
    @type = params[:type]
    @type = "place" unless Subscription.subscribable_classes.map(&:underscore).include?(@type)
    resource_type = @type.camelcase
    @resource = Object.const_get(resource_type).find_by_id(params[:resource_id]) rescue nil
    @subscription = Subscription.new(:user => current_user, :resource_type => resource_type, :resource => @resource)
    if params[:partial] && params[:partial] == "form"
      render :partial => params[:partial], :layout => false
    end
  end

  def edit
    @subscription = Subscription.find_by_id(params[:id]) if params[:id]
    if params[:resource_type] && params[:resource_id]
      @resource = Object.const_get(params[:resource_type]).find_by_id(params[:resource_id]) rescue nil
      if @resource
        @subscription ||= current_user.subscriptions.where(
          resource_type: params[:resource_type], resource_id: params[:resource_id]).first
      end
    end
    return render_404 unless @subscription
    @resource ||= @subscription.resource
    @type = @resource.class.to_s if @resource
    
    if @subscription && @subscription.user_id != current_user.id
      flash[:error] = "You don't have permission to do that"
      return redirect_back_or_default(@subscription.resource)
    end
    
    if (partial = params[:partial]) && partial == 'edit_inline'
      render :partial => partial, :layout => false
      return
    end
  end

  def create
    @subscription = Subscription.new(params[:subscription])
    @subscription.user = current_user
    respond_to do |format|
      if @subscription.save
        format.html do
          flash[:notice] = "Subscription saved."
          return redirect_back_or_default(@subscription.resource)
        end
        format.json { render :json => @subscription }
      else
        msg = "Failed to create subscription: #{@subscription.errors.full_messages.to_sentence}"
        format.html do
          flash[:error] = msg
          return redirect_back_or_default(@subscription.resource || '/')
        end
        format.json do
          render :status => :unprocessable_entity, :json => {:error => msg}
        end
      end
    end
  end
  
  def update
    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html do
          flash[:notice] = "Subscription updated."
          return redirect_back_or_default(@subscription.resource)
        end
        format.json { render json: @subscription }
      else
        format.html { render :action => :edit }
        format.json do
          render :status => :unprocessable_entity, json: { error: @subscription.errors.full_messages.to_sentence }
        end
      end
    end
  end

  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = "Subscription deleted."
        return redirect_back_or_default(@subscription.resource)
      end
      format.json do
        render :status => :ok, :json => {}
      end
    end
  end

  def subscribe
    @subscription = current_user.subscriptions.where(resource: @resource).first
    if !@subscription && (params[:subscribe].nil? || params[:subscribe].yesish?)
      @subscription = Subscription.create(resource: @resource, user: current_user)
    elsif @subscription
      @subscription.destroy
    end
    respond_to do |format|
      format.html { redirect_to @resource }
      format.json { head :no_content }
    end
  end
  
  private
  def load_subscription
    @subscription = if params[:id]
      Subscription.find_by_id(params[:id])
    elsif params[:resource_type] && params[:resource_id]
      current_user.subscriptions.where(
        resource_type: params[:resource_type], resource_id: params[:resource_id]).first
    end
    render_404 unless @subscription
  end

  def load_resource
    subscribable_classes = Subscription.subscribable_classes
    resource_type = if subscribable_classes.include?( params[:resource_type] )
      params[:resource_type]
    end
    return render_404 unless resource_type
    klass = Object.const_get( resource_type )
    if klass.column_names.include?( "uuid" )
      @resource ||= klass.find_by_uuid( params[:resource_id] ) rescue nil
    end
    @resource ||= klass.find_by_id( params[:resource_id] ) rescue nil
    render_404 unless @resource
  end
  
  def require_owner
    unless logged_in? && current_user.id == @subscription.user_id
      flash[:error] = "You don't have permission to do that"
      return redirect_back_or_default(@subscription.resource)
    end
  end
end

app/views/subscriptions/_edit_inline.html.erb
<%- 
  subscription ||= @subscription
  resource = @resource || subscription.resource
%>
<ul class="edit_subscription_inline">
  <% if resource.is_a?(Place) && subscription -%>
    <li>
      <%= form_for subscription, :builder => DefaultFormBuilder do |f| %>
        <div class="field">
          <div>
            <label><%= t :only_receive_updates_about_this_taxon %></label>
          </div>
          <%= text_field_tag :taxon_name, subscription.taxon.try(:name),
            :width => 50,
            :placeholder => t(:type_a_taxon_name, :default => "Type a taxon name"),
            :class => "taxonchooser text" %>
          <%= f.hidden_field(:taxon_id, 
            :alt => (subscription.taxon ? 
              "<span class='taxon sciname #{subscription.taxon.rank} #{Taxon::ICONIC_TAXA_BY_ID[subscription.taxon.iconic_taxon_id].try(:name)}'>#{subscription.taxon.name}</span>" : nil),
            :rel => (subscription.taxon ? taxon_image_url(subscription.taxon) : nil)) %>
        </div>
      <% end -%>
    </li>
  <% end -%>
  <li class="createdestroy">
    <%- new_subscription = Subscription.new(:user => current_user, :resource => resource) %>
    <%= form_for new_subscription, :html => {
      :class => "subscribe",
      :style => "#{'display:none;' if subscription}"
    } do |f| %>
      <%= f.hidden_field :resource_type %>
      <%= f.hidden_field :resource_id %>
      <%= f.hidden_field :user_id %>
      <%= link_to_function t(:subscribe_to_this) + ' ' + t(resource.class.to_s.underscore.humanize.downcase).downcase, "$(this).parents('form:first').submit()" %>
    <% end -%>

    <%= form_tag delete_subscription_url(resource.class.to_s, resource.id), 
        :method => :delete, 
        :class => 'unsubscribe', 
        :style => "#{'display:none;' unless subscription}" do %>
      <%= hidden_field_tag :resource_type, resource.class.to_s %>
      <%= hidden_field_tag :resource_id, resource.id %>
      <%= link_to_function t(:unsubscribe), "$(this).parents('form:first').submit()" %>
    <% end -%>
  </li>
</ul>

app/views/subscriptions/_form.html.haml
= form_for @subscription, :builder => DefaultFormBuilder do |f|
  = f.hidden_field :resource_type, :value => @type.camelcase
  = f.text_field :resource_id, :placeholder => t("choose_a_#{@type.humanize.downcase}".to_sym, default: "choose a taxon"), :required => true, :label => t(@type.to_sym)
  = f.text_field :taxon_id, :placeholder => t(:choose_a_taxon), :label => t(:taxon)
  .inline.stacked.buttonrow
    = f.submit t(:save), :class => "default button", "data-loading-click" => t(:saving)
  .required * #{t(:required).capitalize}

:javascript
  window.defaultTaxa = #{json_escape Taxon::ICONIC_TAXA.to_json(:methods => [:html]).html_safe}

  if ($('#subscription_resource_type').val() == 'Place') {
    $('#subscription_resource_id').chooser({
      collectionUrl: '/places/autocomplete.json?with_geom=t',
      resourceUrl: '/places/{{id}}.json?partial=autocomplete_item',
      afterSelect: function(item) {
        $('#subscription_resource_type').val('Place')
      }
    })
    $('#subscription_taxon_id').chooser({
      collectionUrl: '/taxa/autocomplete.json',
      resourceUrl: '/taxa/{{id}}.json?partial=chooser',
      defaultSources: defaultTaxa
    })
  } else if ($('#subscription_resource_type').val() == 'Taxon') {
    $('#subscription_resource_id').chooser({
      collectionUrl: '/taxa/autocomplete.json',
      resourceUrl: '/taxa/{{id}}.json?partial=chooser',
      defaultSources: defaultTaxa
    })
    $('.taxon_id_field').hide()
  } else {
    $('.taxon_id_field').hide()
  }

app/views/subscriptions/_subscription.html.erb
<%- content_for :extrajs do %>
  <script type="text/javascript" charset="utf-8">
    $( ".subscription form" ).submit( function ( ) {
      $( this ).fadeOut( function ( ) {
        $( this ).siblings( "form" ).fadeIn( );
      } );
      var data = $( this ).serialize() + "&format=json";
      $.ajax( {
        url: $( this ).attr( "action" ),
        type: "post",
        data: data
      } );
      return false;
    } );
    $( ".subscriptionsettings" ).subscriptionSettings( );
    $( ".subscription form .submit-link" ).click( function ( ) {
      $( this ).parents( "form:first" ).submit( );
      return false;
    } );
  </script>
<% end %>
<%- 
  subscription ||= @subscription
  resource ||= subscription.resource if subscription
  resource_type = resource.class.to_s.underscore if resource
  subscription ||= if resource && logged_in?
    current_user.subscriptions.where( resource_type: resource.class.base_class.to_s, resource_id: resource.id ).first
  end
-%>
<div class="meta subscription">
  <%- new_subscription = Subscription.new(:user => current_user, :resource => resource) %>
  <%= form_for new_subscription, :html => {
    :class => "subscribe",
    :style => "#{'display:none;' if subscription}"
  } do |f| %>
    <%= f.hidden_field :resource_type %>
    <%= f.hidden_field :resource_id %>
    <%= f.hidden_field :user_id %>
    <%=
      notifiers = resource.class.notifying_associations.keys.sort
      key = if notifiers.size == 1 && notifiers[0].to_s == "comments"
        "subscribe_to_comments_on_this_#{resource_type}_html"
      else
        "subscribe_to_#{notifiers.join( "_" )}_from_this_#{resource_type}_html"
      end
      t key, tag_start: "<a href='' class='submit-link'>".html_safe, tag_end: "</a>".html_safe, default: t(
        :subscribe_to_x_from_this_y_html, 
        x: commas_and( resource.class.notifying_associations.keys.map{|k| t( k.to_s.underscore ) } ),
        y: t( resource_type )
      )
    %>
  <% end -%>

  <%= form_tag delete_subscription_url( resource.class.base_class.to_s, resource.id ), 
      :method => :delete, 
      :class => 'unsubscribe', 
      :style => "#{'display:none;' unless subscription}" do %>
    <%=
      notifiers = resource.class.notifying_associations.keys.sort
      key = if notifiers.size == 1 && notifiers[0].to_s == "comments"
        "you_are_subscribed_to_comments_on_this_#{resource_type}"
      else
        "you_are_subscribed_to_#{notifiers.join( "_" )}_from_this_#{resource_type}"
      end
      t key
    %>
    <%= hidden_field_tag :resource_type, resource.class.to_s %>
    <%= hidden_field_tag :resource_id, resource.id %>
    <nobr>
      <% if resource.is_a?(Place) -%>
        <%= link_to ("<span class='ui-icon inlineblock ui-icon-gear'></span>" + t(:settings).capitalize).html_safe, edit_subscription_by_resource_url(resource.class.to_s, resource.id),
          :class => "subscriptionsettings" %>
      <% else %>
        <%= link_to_function t(:unsubscribe), "$(this).parents('form:first').submit()" %>
      <% end -%>
    </nobr>
  <% end -%>
</div>

app/views/subscriptions/edit.html.erb
<%- content_for(:title) do -%>
  <%= 
    @title = t(:editing_subscription_to_x_html, :x => link_to(@resource.try_methods(:display_name, :name, :to_s), @resource))
    strip_tags @title
  %>
<%- end -%>
<%- content_for(:extrajs) do -%>
  <%-
    @default_taxa = Taxon::ICONIC_TAXA.map do |taxon|
      taxon.html = render(:partial => "taxa/chooser.html.erb", :object => taxon)
      taxon
    end
    if @subscription.taxon
      @subscription.taxon.html = render(:partial => "taxa/chooser.html.erb", :object => @subscription.taxon)
    end
  -%>
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
      $('#subscription_taxon_id').chooser({
        collectionUrl: '/taxa/autocomplete.json',
        resourceUrl: '/taxa/{{id}}.json?partial=chooser',
        defaultSources: <%=json_escape @default_taxa.to_json(:methods => [:html]).html_safe %>,
        chosen: <%=json_escape @subscription.taxon.to_json.html_safe %>
      })
    })
  </script>
<%- end -%>

<h2>
  <%= @title %>
</h2>

<%= form_for @subscription, :builder => DefaultFormBuilder do |f| %>
  <% if @subscription.resource_type == Place.to_s -%>
    <%= f.text_field :taxon_id, :placeholder => t(:choose_a_taxon), :label => t(:only_receive_updates_about_this_taxon) %>
  <% end -%>
  <%= f.submit t(:update_subscription), :class => "default button" %>
  <%= link_to t(:delete), @subscription, :method => "delete", 
    :data => {:confirm => t(:are_you_sure?, :default => "Are you sure?")}, 
    :class => "delete button" %>
<% end -%>

app/views/subscriptions/index.html.erb
<%- content_for(:title) do -%>
  <%= @title = t(:manage_all_your_subscriptions) %>
<%- end -%>
<div id="pageheader" class="clear">
  <div class="breadcrumbs">
    <strong><%= link_to "&laquo #{t(:back_to_your_dashboard)}".html_safe, dashboard_path, class: "crumb" %></strong>
  </div><!-- /#breadcrumbs -->
  <h2><%= @title %></h2>
</div>

<div class="column span-4">
  <ul class="leftmenu">
    <% for klass in Subscription.subscribable_classes.sort %>
      <li>
        <%= link_to t( klass.underscore.pluralize, default: klass ),
          url_for( type: klass.underscore ),
          class: @type == klass.underscore ? "active" : nil
        %>
      </li>
    <% end %>
  </ul>
</div>
<div class="last column span-20">
  <% if @subscriptions.blank? -%>
    <div class="noresults meta"><%= t :no_results_found %></div>
  <%- else %>
    <table border="0" cellspacing="5" cellpadding="5" width="100%">
      <thead>
        <tr>
          <th><%= t :resource, default: 'Resource' %></th>
          <th><%= t :actions, default: 'Actions' %></th>
        </tr>
      </thead>
      <tbody>
        <% for subscription in @subscriptions %>
          <tr>
            <td>
              <%=t subscription.resource_type.parameterize.underscore, default: subscription.resource_type %> <%= subscription.resource_id %>:
              <% name = subscription.resource.try_methods(:to_plain_s, :login, :name, :title, :to_s) %>
              <%= link_to name, subscription.resource %>
            </td>
            <td class="nobr meta">
              <% if subscription.resource_type == "Place" -%>
                <%= link_to t(:edit), edit_subscription_url(subscription) %>
                |
              <% end -%>
              <%= link_to t(:unsubscribe), subscription_url(subscription), :method => "delete",
                :data => {:confirm => t(:are_you_sure_you_want_to_unsubscribe_from_this, default: 'Are you sure you want to unsubscribe from this?')} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @subscriptions %>
  <% end -%>
</div>

app/views/subscriptions/new.html.haml
= content_for :title do
  = @title = "New #{@type.humanize.downcase} subscription"
%h2= @title
= render 'form'