config/routes.rb
      delete :destroy_synonyms, :as => 'delete_synonyms_of'
    end
  end
  # get 'taxa/:id/description' => 'taxa#describe', :as => :describe_taxon
  patch 'taxa/:id/graft' => 'taxa#graft', :as => :graft_taxon
  get 'taxa/:id/children' => 'taxa#children', :as => :taxon_children
  get 'taxa/:id/children.:format' => 'taxa#children', :as => :formatted_taxon_children
  get 'taxa/:id/photos' => 'taxa#photos', as: :photos_of_taxon
  put 'taxa/:id/update_colors' => 'taxa#update_colors', :as => :update_taxon_colors
  match 'taxa/:id/add_places' => 'taxa#add_places', :as => :add_taxon_places, :via => [:get, :post]
  get 'taxa/flickr_tagger' => 'taxa#flickr_tagger', :as => :flickr_tagger
  get 'taxa/flickr_tagger.:format' => 'taxa#flickr_tagger', :as => :formatted_flickr_tagger
  post 'taxa/tag_flickr_photos'
  get 'taxa/flickr_photos_tagged'
  post 'taxa/tag_flickr_photos_from_observations'
  get 'taxa/search' => 'taxa#search', :as => :search_taxa
  get 'taxa/search.:format' => 'taxa#search', :as => :formatted_search_taxa
  get 'taxa/:action.:format' => 'taxa#index', :as => :formatted_taxa_action
  match 'taxa/:id/merge' => 'taxa#merge', :as => :merge_taxon, :via => [:get, :post]
  get 'taxa/:id/merge.:format' => 'taxa#merge', :as => :formatted_merge_taxon
  get 'taxa/:id/observation_photos' => 'taxa#observation_photos', :as => :taxon_observation_photos
  get 'taxa/observation_photos' => 'taxa#observation_photos'
  get 'taxa/:id/map' => 'taxa#map', :as => :taxon_map
  get 'taxa/map' => 'taxa#map', :as => :taxa_map
  get 'taxa/:id/range.:format' => 'taxa#range', :as => :taxon_range_geom
  get 'taxa/auto_complete_name' => 'taxa#auto_complete_name'
  get 'taxa/occur_in' => 'taxa#occur_in'
  get '/taxa/curation' => 'taxa#curation', :as => :curate_taxa
  get "taxa/*q" => 'taxa#try_show'
  
  resources :sources
  get 'journal' => 'posts#browse', :as => :journals
  get 'journal/:login' => 'posts#index', :as => :journal_by_login, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/' => 'posts#archives', :as => :journal_archives, :constraints => { :login => simplified_login_regex }
  get 'journal/:login/archives/:year/:month' => 'posts#archives', :as => :journal_archives_by_month, :constraints => { :month => /\d{1,2}/, :year => /\d{1,4}/, :login => simplified_login_regex }
  get 'journal/:login/:id/edit' => 'posts#edit', :as => :edit_journal_post
  resources :posts, :except => [:index], :constraints => { :id => id_param_pattern } do
    resources :flags
    collection do
      get :for_project_user
      get :for_user
    end
  end
  resources :posts,
    :as => 'journal_posts',
    :path => "/journal/:login",
    :constraints => { :login => simplified_login_regex } do
    resources :flags
  end
  resources :posts, as: "site_posts", path: "/blog" do
    resources :flags
    collection do
      get "archives/:year/:month" => "posts#archives", as: :archives_by_month, constraints: {
        month: /\d{1,2}/, 
        year: /\d{1,4}/
      }
      get :archives
    end
  end
  resources :trips, :constraints => { :id => id_param_pattern } do
    member do
      post :add_taxa_from_observations
      delete :remove_taxa
    end
    collection do
      get :tabulate
    end
  end
  get 'trips/:login' => 'trips#by_login', :as => :trips_by_login, :constraints => { :login => simplified_login_regex }
  
  resources :identifications, :constraints => { :id => id_param_pattern } do
    resources :flags
  end
  get 'identifications/bold' => 'identifications#bold'
  post 'identifications/agree' => 'identifications#agree'
  get 'identifications/:login' => 'identifications#by_login', :as => :identifications_by_login, :constraints => { :login => simplified_login_regex }
  resources :taxon_links
  
  get 'places/:id/widget' => 'places#widget', :as => :place_widget
  get 'places/guide_widget/:id' => 'places#guide_widget', :as => :place_guide_widget
  post '/places/find_external' => 'places#find_external', :as => :find_external
  get '/places/search' => 'places#search', :as => :place_search
  get '/places/:id/children' => 'places#children', :as => :place_children
  get 'places/:id/taxa.:format' => 'places#taxa', :as => :place_taxa
  get 'places/geometry/:id.:format' => 'places#geometry', :as => :place_geometry
  get 'places/guide/:id' => 'places#guide', :as => :place_guide
  get 'places/guide' => 'places#guide', :as => :idendotron_guide
  get 'places/cached_guide/:id' => 'places#cached_guide', :as => :cached_place_guide
  get 'places/autocomplete' => 'places#autocomplete', :as => :places_autocomplete
  resources :places do
    collection do
      get :planner
    end
    member do
      get :merge
      post :merge
    end
  end

  resources :flags
  resource :admin, only: :index, controller: :admin do
    collection do
      get :index
      get :queries
      get :stop_query
      get :users
      get "users/:id" => "admin#user_detail", as: :user_detail
      get :deleted_users
      put :grant_user_privilege
      put :revoke_user_privilege
      put :restore_user_privilege
      put :reset_user_privilege
    end
    resources :delayed_jobs, only: :index, controller: "admin/delayed_jobs" do
      member do
        get :unlock
      end
      collection do
        get :index
        get :active
        get :failed
        get :pending
      end
    end
  end
  get 'admin/user_content/:id/(:type)', :to => 'admin#user_content', :as => "admin_user_content"
  delete 'admin/destroy_user_content/:id/:type', :to => 'admin#destroy_user_content', :as => "destroy_user_content"
  put 'admin/update_user/:id', :to => 'admin#update_user', :as => "admin_update_user"

  resources :site_admins, only: [:create, :destroy] do
    collection do
      delete :destroy
    end
  end

  resource :stats do
    collection do
      get :index
      get :summary
      get :observation_weeks
      get :nps_bioblitz
      get :cnc2016
      get :cnc2017
      get :cnc2017_taxa
      get :cnc2017_stats
      get :canada_150
      get :parks_canada_2017
      get ":year", as: "year", to: "stats#year", constraints: { year: /\d+/ }
      get ":year/you", as: "your_year", to: "stats#your_year", constraints: { year: /\d+/ }
      get ":year/:login", as: "user_year", to: "stats#year", constraints: { year: /\d+/ }
      post :generate_year
    end
  end

  resources :taxon_ranges, :except => [:show]
  
  resources :atlases do
    member do
      post :alter_atlas_presence
      post :destroy_all_alterations
      post :remove_atlas_alteration
      post :remove_listed_taxon_alteration
      post :refresh_atlas
      get :get_defaults_for_taxon_place
    end
  end
  resources :exploded_atlas_places
  
  resources :complete_sets do
    member do
      post :destroy_relevant_listings
      post :remove_listed_taxon_alteration
      get :get_relevant_listings
    end
  end
  
  get '/calendar/:login' => 'calendars#index', :as => :calendar
  get '/calendar/:login/compare' => 'calendars#compare', :as => :calendar_compare
  get '/calendar/:login/:year/:month/:day' => 'calendars#show', :as => :calendar_date, :constraints => {
    :year => /\d+/,
    :month => /\d+/,
    :day => /\d+/
  }
  
  resources :subscriptions, :only => [:index, :new, :edit, :create, :update, :destroy]
  delete 'subscriptions/:resource_type/:resource_id' => "subscriptions#destroy", :as => :delete_subscription
  get 'subscriptions/:resource_type/:resource_id/edit' => "subscriptions#edit", :as => :edit_subscription_by_resource
  post 'subscriptions/:resource_type/:resource_id/subscribe' => 'subscriptions#subscribe', as: :subscribe

  resources :taxon_changes, constraints: { id: id_param_pattern } do
    resources :taxon_change_taxa, controller: :taxon_change_taxa, shallow: true
    collection do
      get "group/:group" => "taxon_changes#group", as: :group
    end
    put :commit
    get :commit_for_user
    put "commit_record/:type/:record_id/to/:taxon_id" => "taxon_changes#commit_records", as: :commit_record
    put "commit_records/:type/(to/:taxon_id)" => "taxon_changes#commit_records", as: :commit_records
  end
  resources :taxon_schemes, :only => [:index, :show], :constraints => {:format => [:html]}
  get 'taxon_schemes/:id/mapped_inactive_taxa' => 'taxon_schemes#mapped_inactive_taxa', :as => :mapped_inactive_taxa
  get 'taxon_schemes/:id/orphaned_inactive_taxa' => 'taxon_schemes#orphaned_inactive_taxa', :as => :orphaned_inactive_taxa
  
  resources :taxon_framework_relationships
  get 'taxon_frameworks/:id/relationship_unknown' => 'taxon_frameworks#relationship_unknown', :as => :relationship_unknown
  
  resources :taxon_frameworks, except: [:show, :index]
  
  resources :taxon_splits, :controller => :taxon_changes
  resources :taxon_merges, :controller => :taxon_changes
  resources :taxon_swaps, :controller => :taxon_changes
  resources :taxon_drops, :controller => :taxon_changes
  resources :taxon_stages, :controller => :taxon_changes
  resources :conservation_statuses, :only => [:autocomplete]

  resource :computer_vision_demo, only: :index, controller: :computer_vision_demo do
  end
  resources :computer_vision_demo_uploads do
    member do
      post :score
    end
  end
  resources :user_parents, only: [:index, :new, :create, :destroy] do
    member do
      get :confirm
    end
  end
  resources :moderator_actions, only: [:create]

  resource :lifelists, only: [] do
    collection do
      get ":login", to: "lifelists#by_login", as: "by_login"
    end
  end

  get "/google_photos(/:action(/:id))", controller: :picasa

  get 'translate' => 'translations#index', :as => :translate_list
  post 'translate/translate' => 'translations#translate', :as => :translate
  get 'translate/reload' => 'translations#reload', :as => :translate_reload

  # Hack to enable mail previews. You could also remove get
  # '/:controller(/:action(/:id))' but that breaks a bunch of other stuff. You
  # could also fix that other stuff, if you're weren't a horrible person, but
  # you are.

app/views/identifications/_box.html.erb
<%-
  identification ||= box
  observation ||= @observation
  skip_body ||= false
-%>
<div class="identification <%= identification.user_id == observation.user_id ? 'box' : 'quiet box' %>">
  <div class="boxheader">
    <% if is_me? identification.user -%>
      <%=t :your_id %>
    <% else %>
      <%=t :users_id, :user => identification.user.login %>
    <% end -%>
  </div>
  <div class="boxbody ui-helper-clearfix">
    <%= image_and_content link_to(user_image(identification.user, :size => "thumb"), identification.user) do %>
      <%= image_and_content link_to(taxon_image(identification.taxon), identification.taxon) do %>
        <% if logged_in? && identification.user_id != current_user.id -%>
          <%= link_to t(:agree?), {
               :controller => 'identifications',
               :action => 'agree',
               :observation_id => identification.observation_id,
               :taxon_id => identification.taxon_id },
             :method => :post,
             "data-loading-click" => "...",
             :class => "glaucous button" %>
        <% end -%>
        <div class="stacked">
          <%= render :partial => "shared/taxon", :object => identification.taxon, :locals => {
            :link_url => url_for(identification.taxon),
            :include_parens => false,
            :named_ancestor => true
          } %>
        </div>
      <% end -%>
    <% end -%>
    <% if !identification.body.blank? && !skip_body -%>
      <%= formatted_user_text identification.body %>
    <% end -%>
  </div>
</div>

app/views/identifications/_form_fields.html.erb
<%- show_body ||= false -%>
<%- body_label ||= t(:remarks_optional).html_safe -%>
  <div class="field species_guess_field">
    <label for="identification_species_guess-<%= identification.observation_id %>"><%=t :species%></label>
    <%= text_field_tag(:species_guess, '',
      :placeholder => t(:type_species_name),
      :size => '', 
      :class => 'text species_guess',
      :id => "identification_species_guess-#{identification.observation_id}") %>
    <%= f.hidden_field :taxon_id, class: "ac_hidden_taxon_id",
                       :id => "identification_taxon_id-#{identification.observation_id}" -%>
  </div>
  <% if show_body -%>
    <div class="field body_field">
      <%= f.label :body, body_label.html_safe %>
      <%= f.text_area :body, maxlength: Comment::MAX_LENGTH %>
    </div>

    <div class="field">
      <%= f.check_box :captive_flag %>
      <%= f.label :captive_flag, t(:organism_appears_captive_cultivated) %>
      <% helptip_for "captive_flag" do %>
        <%=t 'views.observations.captive_help_html' %>
      <% end -%>
    </div>
  <% end -%>

  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :observation_id %>

app/views/identifications/_identification.html.erb
<%
  identification ||= @identification
  taxon ||= identification.taxon
  observation ||= identification.observation
  user ||= identification.user
  viewers_identification ||= @viewers_identification
  usertext ||= nil
  identification_classes = ''
  if logged_in? && identification.user_id == current_user.id
    identification_classes += ' yours'
  end
  if identification.user_id == observation.user_id
    identification_classes += ' owners'
  end
  identification_classes += " #{identification.current? ? 'current' : 'outdated'}"
  hide_actions ||= false
  hide_agree ||= false
  extra ||= nil
-%>
<div id="<%= id_for(identification) %>" class="clear identification <%= identification_classes %>" data-taxon-id="<%= taxon.id if taxon %>">
  <div class="identification_image">
    <%= link_to taxon_image(taxon), taxon %>
  </div>
  <div class="identification_body">
    <span class="user_and_taxon">
      <span class="user">
        <% if user -%>
          <% if is_me?(user) %>
            <%=t :label_colon, label: t(:your_id) %>
          <% else %>
            <%=t( :label_colon, label: link_to( t(:users_id, user: user.login), person_path( user ) ).html_safe ).html_safe %>
          <% end %>
        <% elsif usertext %>
          <%= usertext %>
        <% end -%>
      </span>
      <%= render :partial => 'shared/taxon', 
                 :locals => { :taxon => taxon,
                              :link_url => taxon,
                              :named_ancestor => true } %>
    </span>
    <% unless hide_actions -%>
      <% if logged_in? && 
          !hide_agree &&
          identification.user_id != current_user.id && 
          (viewers_identification.blank? || viewers_identification.taxon_id != identification.taxon_id) %>
        <span class="agree button">
          <%= link_to t(:agree?), {
               :controller => 'identifications',
               :action => 'agree',
               :observation_id => identification.observation_id,
               :taxon_id => identification.taxon_id },
             :method => :post,
             "data-loading-click" => t(:agreeing) -%></span>
      <% end %>
      <% if logged_in? && identification.user_id == current_user.id && identification.current? %>
        <span class="button withdrawbutton"><%= link_to t(:withdraw), identification_path( identification ),
            method: :delete,
            "data-loading-click" => t(:withdrawing),
            class: "removelink" -%></span>
      <% end %>
    <% end -%>
    
    <%= extra if extra %>
    
    <% unless taxon.is_active -%>
      <span class="small meta">
        (<%= link_to t(:inactive_taxon), taxon_changes_path(:taxon_id => taxon.id) -%>)
      </span>
    <% end -%>

    <% if tc = identification.taxon_change -%>
      <span class="small meta nobr">
        <% if tc.is_a? TaxonSwap %>
          <%= t :added_as_a_part_of_a_taxon_swap_html, target: "_self", url: taxon_change_path(tc), class: "taxon_change_link" %>
        <% elsif tc.is_a? TaxonMerge %>
          <%= t :added_as_a_part_of_a_taxon_merge_html, target: "_self", url: taxon_change_path(tc), class: "taxon_change_link" %>
        <% elsif tc.is_a? TaxonSplit %>
          <%= t :added_as_a_part_of_a_taxon_split_html, target: "_self", url: taxon_change_path(tc), class: "taxon_change_link" %>
        <% else %>
          <%= t :added_as_a_part_of_a_taxon_change_html, target: "_self", rl: taxon_change_path(tc), class: "taxon_change_link" %>
        <% end %>
      </span>
    <% end -%>

    <%= feature_test :idcats, audience: [:users] do %>
      <div class="small status">
        <%= identification.category %>
      </div>
    <% end %>
  </div>
</div>

app/views/identifications/_identification_for_dashboard.html.erb
<%
  identification ||= @identification
  taxon ||= identification.taxon
  observation ||= identification.observation
  user ||= identification.user
  viewers_identification ||= @viewers_identification
  usertext ||= nil
  identification_classes = ''
  if logged_in? && identification.user_id == current_user.id
    identification_classes += ' yours'
  end
  if identification.user_id == observation.user_id
    identification_classes += ' owners'
  end
  hide_actions ||= false
  hide_agree ||= false
  extra ||= nil
-%>
  <div class="media">
    <div class="media-left">
      <%= link_to taxon_image(taxon, :class => "media-object img-thumbnail", :style => "width:50px;height:50px;"), taxon %>
    </div>
    <div class="media-body">
      <% unless hide_actions -%>
        <% if logged_in? && 
            !hide_agree &&
            identification.user_id != current_user.id && 
            (viewers_identification.blank? || viewers_identification.taxon_id != identification.taxon_id) %>
          <span class="btn btn-sm btn-default btn_agree">
            <%= link_to t(:agree?), {
                 controller: "identifications",
                 action: "agree",
                 observation_id: identification.observation_id,
                 taxon_id: identification.taxon_id },
               method: :post,
               target: "_blank" -%>
          </span>
        <% end %>
        <% if logged_in? && identification.user_id == current_user.id && identification.current? %>
          <span class="btn btn-sm btn-default btn_agree"><%= link_to t(:remove), identification_path(identification),
              :method => :delete,
              "data-loading-click" => t(:removing),
              :class => "removelink" -%></span>
        <% end %>
      <% end -%>
      <% unless identification.current? -%>
        <span class="label label-default label_refined">Refined</span>
      <% end -%>
      <h3 class="dashboard_id">
        <%= render :partial => 'shared/taxon', 
                   :locals => { :taxon => taxon,
                                :link_url => taxon,
                                :named_ancestor => false } %>        
      </h3>

    



  </div>
</div>

app/views/identifications/_identification_form.html.erb
<%-
  identification_form ||= nil
  identification ||= identification_form
-%>
<% if logged_in? %>
  <%- identification ||= Identification.new(:user => current_user, 
                                           :observation => observation) -%>
  <%= form_for(identification, :remote => true,
    :html => {
      "data-type" => "json",
     :id => "new_identification-#{observation.id}",
     :class => "identificationform"
    }) do |f| %>
    
    <%= render :partial => 'identifications/form_fields', :locals => {
      :identification => identification,
      :f => f
    } %>

    <div class="buttonrow" style="text-align:center">
      <%= image_tag('spinner.gif', 
        :id => "new_identification-#{observation.id}-loading", 
        :class => 'loading inlineblock', 
        :style => 'display: none') %>
      <%= f.submit(t(:save), :class => 'default button inlineblock', :tabindex => observation.id+1) %>
    </div>
  <% end %>
<% else %>
  <%= link_to t(:sign_in), login_path %>
  <%=t :or %> <%= link_to t(:sign_up), signup_path %>
  <%=t :to_add_ids %>
<% end %>

app/views/identifications/_identification_with_observation.html.erb
<%- identification ||= identification_with_observation || @identification -%>
<div class="mini <%= 'compact' if request.format.mobile? %> observations observationcol column span-8">
  <%= render :partial => "observations/cached_component", :locals => { 
    :observation => identification.observation } %>
</div>
<div class="identificationcol last column span-10">
  <%- extra = capture do -%>
    <div class="small description">
     <%=t :added_on_datetime, datetime: l( identification.created_at.to_date, format: :month_day_year ) %>.
     <div class="ident-category">
       <%=t identification.category, default: identification.category %>
     </div>
    </div>
  <%- end -%>
  <%= render :partial => "identifications/identification", :locals => { 
    :identification => identification,
    :extra => extra
  } %>
</div>

app/views/identifications/by_login.html.erb
<% content_for(:title)  do %>
  <%= t(:identifications_by, :user=> @login) %>
<% end %>
<% content_for(:extracss) do %>
<%= stylesheet_link_tag 'identifications' %>
<style type="text/css" media="screen">
  .identification {
    padding: 10px;
    background-color: #eee;
  }
  
  .observations.mini .observation {
    padding: 10px 0;
    margin-bottom: 0;
    border: 0;
  }
  
  .identification .identification_image {width: 75px;}
  .identification .identification_body {float: left;}
  
  .row {
    margin-bottom: 10px;
    border-bottom: 1px solid #eee;
  }
  
  .count {
    font-weight: bold;
  }
</style>
<!--[if lte IE 7]>
  <%= stylesheet_link_tag 'blueprint/ie', 'observations-ie' %>
<![endif]-->
<% end %>

<%= render :partial => "shared/by_login_header" %>

<div id="identifications" class="column span-18">
  <% if @identifications.empty? -%>
    <div id="no_content" class="readable description">
      <% if logged_in? && @selected_user.id == current_user.id %>
        <%= t 'no_identifications_added.current_user' %>
      <% else %>
        <%= t 'no_identifications_added.user', user: @login.to_s %>
      <% end %>
    </div>
  <% end -%>
  <% for identification in @identifications %>
    <div class="row column span-18">
      <%= render :partial => 'identification_with_observation', :object => identification %>
    </div>
  <% end %>
  
  <%= will_paginate @identifications, :renderer => INatLinkRenderer %>
</div>

<div class="last column span-6">
  <div class="box">
    <h3><%=t :stats %></h3>
    <ul>
      <li>
        <span class="count"><%= @identifications.total_entries %></span>
        <label><%=t :ids_made_for_others %></label>
      </li>
    </ul>
  </div>
</div>

app/views/identifications/edit.html.haml
- content_for(:title) do
  = t :edit_your_identification
- content_for(:extracss) do
  = stylesheet_link_tag "identifications"
  :css
    .observations.mini .observation {
      border-bottom: 0 transparent;
    }
- content_for(:extrajs) do
  = javascript_include_tag "identifications/edit"
.container
  .row
    .col-xs-12
      %h2= t :edit_your_identification
  .row
    .col-xs-6
      %h3=t :observation
      .mini.observations
        = render "observations/cached_component", observation: @identification.observation
    .col-xs-6
      %h3= t :your_identification
      = render "identifications/identification", identification: @identification, hide_actions: true
      = form_for @identification, builder: BootstrapFormBuilder do |f|
        = f.text_area :body, label: t(:remarks_optional), maxlength: Comment::MAX_LENGTH
        = submit_tag t(:save_identification), :class => 'default button'
        - unless @identification.new_record?
          = link_to t(:cancel), url_for(@identification.observation) + "##{id_for(@identification)}", :class => 'button'
        .pull-right
          - if @identification.current?
            = link_to t(:withdraw), identification_path( @identification ), method: :delete, class: "minor delete button right", data: { loading_click: t(:withdrawing) }
          - else
            = link_to t(:restore), identification_path( @identification, identification: { current: true } ), method: :put, class: "minor button", data: { loading_click: t(:restoring) }
          = link_to t(:delete), identification_path( @identification, delete: true ), method: :delete, class: "minor delete button", data: { loading_click: t(:deleting), confirm: t(:are_you_sure?) }

app/views/identifications/index.html.haml
- content_for(:extrajs) do
  = javascript_include_tag "https://www.gstatic.com/charts/loader.js"
  :javascript
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var counts = [
        ["Category", "Count"]
      ];
      counts = counts.concat( #{@counts.to_a.sort_by(&:first).to_json.html_safe} );
      var data = google.visualization.arrayToDataTable( counts );
      var options = {
        legend: {
          position: "bottom"
        },
        chartArea: { width: "100%", top: 10 }
      };
      var chart = new google.visualization.PieChart(document.getElementById('category-pie'));
      chart.draw(data, options);
    }
- content_for :extracss do
  :css
    .observations.mini .photos {
      float: left;
      margin: 0 10px 0 0;
    }
    .taxonimage .attribution { display: none; }
    .taxonimage { float: left; margin-right: 10px; }
.container
  .row
    .col-xs-12
      %h2=t :identifications
  .row
    .col-xs-9
      %table.table
        %thead
          %tr
            %th id
            %th observation
            %th taxon
            %th user
            %th category
            %th current
            %th vision
            %th blind
            %th disagreement with
        %tbody
          - @identifications.each do |i|
            %tr
              %td= i.id
              %td
                .observations.mini.compact
                  = render "observations/cached_component", observation: i.observation
                  = link_to "View with test=idcats", observation_url( i.observation, test: "idcats" )
              %td
                .taxon_links
                  = render "taxa/taxon", taxon: i.taxon, url: i.taxon, hide_wikipedia_summary: true
              %td= link_to_user i.user
              %td= i.category
              %td= i.current
              %td= i.vision
              %td= i.blind
              %td
                - if i.disagreement? && i.previous_observation_taxon
                  = render "shared/taxon", taxon: i.previous_observation_taxon, link_url: i.previous_observation_taxon
                - elsif i.disagreement?
                  true
      = will_paginate
    .col-xs-3
      %h3 Stats
      #category-pie
      %h3 Params
      %ul
        %li
          %code taxon_id=1234
        %li
          %code user_id=kueda
        %li
          %code category=maverick
        %li
          %code current=false|any
          Default: true
        %li
          %code for=self|others|any
          Default: any